In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [12]:
#sentances
#one hot
#one hot -> embedding layer keras to form embedding matrix
#embedding matrix

In [7]:
sent = [
      'the glass of milk',
      'the glass of softdrink',
      'the cup of coffee',
      'i am a good boy',
      'i am a good student',
      'you are born to rock',
      'i got classes from 6',
]

In [8]:
sent

['the glass of milk',
 'the glass of softdrink',
 'the cup of coffee',
 'i am a good boy',
 'i am a good student',
 'you are born to rock',
 'i got classes from 6']

In [9]:
#size of dictionaart
voc_size = 10000

In [16]:
#one hot rep
onehot_repr = [ one_hot(words,voc_size)for words in sent]
print(onehot_rep)

[[1019, 3779, 2028, 1103], [1019, 3779, 2028, 9559], [1019, 1218, 2028, 9480], [5765, 8240, 679, 6711, 3828], [5765, 8240, 679, 6711, 6280], [7565, 4425, 1462, 9401, 8588], [5765, 5639, 8907, 4980, 5111]]


In [17]:
#word embedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential



In [18]:
import numpy as np

In [20]:
sent_length = 8
#padding to balance number of words
embedded_docs = pad_sequences(onehot_repr,padding = 'pre',maxlen = sent_length)
print(embedded_docs)

[[   0    0    0    0 1019 3779 2028 1103]
 [   0    0    0    0 1019 3779 2028 9559]
 [   0    0    0    0 1019 1218 2028 9480]
 [   0    0    0 5765 8240  679 6711 3828]
 [   0    0    0 5765 8240  679 6711 6280]
 [   0    0    0 7565 4425 1462 9401 8588]
 [   0    0    0 5765 5639 8907 4980 5111]]


In [21]:
dim = 10

In [27]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [28]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)              │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [24]:
print(model.predict(embedded_docs))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 192ms/step
[[[-0.03089046 -0.0218661  -0.03290015  0.01952196 -0.0456816
    0.03225482  0.00833511 -0.01352763 -0.04765964  0.03253002]
  [-0.03089046 -0.0218661  -0.03290015  0.01952196 -0.0456816
    0.03225482  0.00833511 -0.01352763 -0.04765964  0.03253002]
  [-0.03089046 -0.0218661  -0.03290015  0.01952196 -0.0456816
    0.03225482  0.00833511 -0.01352763 -0.04765964  0.03253002]
  [-0.03089046 -0.0218661  -0.03290015  0.01952196 -0.0456816
    0.03225482  0.00833511 -0.01352763 -0.04765964  0.03253002]
  [ 0.03846845  0.02990447  0.04119355 -0.03662959 -0.02508295
    0.00397471 -0.0319934   0.03827028  0.03716923  0.00119952]
  [-0.01382742 -0.02193712  0.01124404  0.00357734 -0.04398931
    0.00193711  0.03107268  0.01962615  0.01103927  0.01293718]
  [-0.02773873  0.03228818  0.00195213 -0.01766466  0.03179332
    0.0358181  -0.02356896  0.01394757 -0.02191727  0.03758112]
  [ 0.03948264 -0.0239614  -0.00987737 -0.03899108 -0.02184845
   -0.0089024

In [25]:
embedded_docs[0]

array([   0,    0,    0,    0, 1019, 3779, 2028, 1103], dtype=int32)

In [26]:
print(model.predict(embedded_docs)[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
[[-0.03089046 -0.0218661  -0.03290015  0.01952196 -0.0456816   0.03225482
   0.00833511 -0.01352763 -0.04765964  0.03253002]
 [-0.03089046 -0.0218661  -0.03290015  0.01952196 -0.0456816   0.03225482
   0.00833511 -0.01352763 -0.04765964  0.03253002]
 [-0.03089046 -0.0218661  -0.03290015  0.01952196 -0.0456816   0.03225482
   0.00833511 -0.01352763 -0.04765964  0.03253002]
 [-0.03089046 -0.0218661  -0.03290015  0.01952196 -0.0456816   0.03225482
   0.00833511 -0.01352763 -0.04765964  0.03253002]
 [ 0.03846845  0.02990447  0.04119355 -0.03662959 -0.02508295  0.00397471
  -0.0319934   0.03827028  0.03716923  0.00119952]
 [-0.01382742 -0.02193712  0.01124404  0.00357734 -0.04398931  0.00193711
   0.03107268  0.01962615  0.01103927  0.01293718]
 [-0.02773873  0.03228818  0.00195213 -0.01766466  0.03179332  0.0358181
  -0.02356896  0.01394757 -0.02191727  0.03758112]
 [ 0.03948264 -0.0239614  -0.00987737 -0.03899108 -0.02184845 -0.00890249
   0.02270302 